### ISSUE TITLE
v1.3.0 Release Checklist Due 2018-10-09

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1104]
Remaining actions:

* [x] Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Coordinate announcements for blog, newsletter, etc with marketing (product owner)
* [x] Create release (release manager)
* [ ] Update Roadmap (TPM/release manager)
* [ ] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
Proposed Release Testing Plan for v1.3.0 (This obsoletes the [place it was written](https://www.evernote.com/l/AA9AIT1UFkRFeJ0mVlSV5-EKXXzEG5GWgx0) and it can be edited here. 

There's a lot in here, so it will be important to watch for regressions of *other* things when testing any single thing. 

I (Randy) plan to test exclusively on Windows for this release. I've already had quite a lot of time on macOS, which tracks very well with Linux.

1. MariaDB 10.2:
    * `ddev ssh -s db` and `mysql` to verify that MariaDB has been upgraded to 10.2.
    * Start a project with ddev v1.2; load the database. rm and start the project with ddev v1.3. `ddev logs -s db` should show mysql_upgrade happening, and should happen without errors. 
    * Try to restore a pre-v1.3 snapshot. You should get a good helpful error.
    * And of course, all normal things like loading databases.
2. Windows Apache support (and https redirects)
    * On Windows, create a TYPO3 v9 LTS project using composer (preferably inside container). 
    * Do the install process using https not http
    * You should be able to log into the backend at the end (admin) successfully, still as https.
3. Container logs
    * `ddev logs` or `ddev logs -s web` should provide full info about nginx, apache, and php activities. So this needs to be tried using both apache and nginx. Create an error and make sure you see the error.
    * `ddev logs -s db` should show full information about mariadb server startup and errors. You can create a major error by `ddev ssh -s db` and  `rm /var/lib/mysql/mysql/*.MYD`, then `ddev restart`
4. Webserver healthcheck
    * `docker inspect --format='{{json .State.Health }}' ddev-<project>-web` should show significant healthcheck information.
    * You should be able to break the healthcheck by removing the /phpstatus stanza from nginx or apache config, so then phpstatus will be an error and thus web container status unhealthy.
5. New php packages and locales
    * You should be able to use php-imagick as the graphics processor in a drupal site. See instructions in https://github.com/drud/ddev/pull/1113
    * You should be able to set the locale for the webserver, See instructions for testing at https://github.com/drud/ddev/pull/1106 (But you don't have to change the webimage). 
    * You should be able to create a drupal site using sqlite at install time. 
6. In-container http access: Curl the project URL from within the web container as both http and https. It should retrieve the front page. 
7. Verify that `drush php` works correctly inside the web container of a Drupal project. See #1130
8. Wordpress settings: 
    * Create a wordpress project with no wp-config.php already existing. ddev should create a valid wp-config.php and wp-config-ddev.php. Test for working project.
    * Create a wordpress project with an alread-existing wp-config.php. ddev should create a wp-config-ddev.php and prompt you how to configure the existing wp-config.php. Test for working project.
    * Load a database which does *not* have the same URL as the project name you're using. Make sure that a set of URLs work correctly (WP_HOME should be set).
9. Try `ddev pull` with pantheon and the new args to omit downloading files.

**Comment by rfay** [comment]
Randy's review (will be updated as I go forward):
* mariadb upgrade: **Regression**: As noted in https://github.com/drud/ddev/issues/1170, the workaround for restoring old snapshots does not work. Otherwise, everything seem fine.

**Comment by rfay** [comment]
IMO based on https://github.com/drud/ddev/issues/1104#issuecomment-429030881 this is almost ready. 
* I think we have to make snapshots available to people with some kind of approach, so solving the first regression is critical for this release.
* I don't think we have to solve the WordPress regressions/problems on Windows in this release, and would like to have as little churn as possible.

I think as soon as we've tested and pulled something for that first snapshot regression we should get pulling and building.

**Comment by rfay** [comment]
It's released! https://github.com/drud/ddev/releases/tag/v1.3.0

**Comment by dclear** [comment]
update roadmap, close milestone and project, spin up next release checklist
