### ISSUE TITLE
1.1-Local-Q4-18: ddev should support direct use of composer in container for create-project, install, and update.

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1185]
## Key Result Description

ddev should support direct use of composer in container for create-project, install, and update. This may be a "ddev composer" command

## Acceptance Criteria

- [x] required [issues](https://github.com/drud/ddev/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+composer) stubbed and estimated
- [x] MVP issues added to this epic
- [ ] Reviewed with team
