### ISSUE TITLE
6.1-Local-Q4-18: Release artifacts are uploaded to the Github release automatically

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1209]
## Key Result Description

Release artifacts are uploaded to the Github release automatically

## Acceptance Criteria

- [x] required issues stubbed and estimated
- [x] MVP issues added to this epic
- [ ] Reviewed with team
