### ISSUE TITLE
v1.5.0 Release Checklist Due 2018-12-18

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1293]
Remaining actions:

* [ ] Review release (product owner)
* [ ] Approve release (product owner and release manager)
* [ ] Create binaries (any DRUD maintainer)
* [ ] Draft release notes (release manager)
* [ ] Coordinate announcements for blog, newsletter, etc with marketing (product owner)
* [ ] Create release (release manager)
* [ ] Update Roadmap (TPM/release manager)
* [ ] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
I note that php7.3 will be released on December 13, so 12/18 is the perfect date for a release that includes php7.3. Doing the PR now.

**Comment by rfay** [comment]
Proposed Test Plan for v1.5.0 - Feel free to add or comment.

The basic idea here is to give the release candidate lots of exercise, so these are just a starting place. We do want to hit all these, but the big idea is to do a large variety of things and look for regressions.

1. **MariaDB 10.1 Support**: 
    * `ddev rm -RO` and `ddev config --mariadb-version=10.1`. Verify correct setting in .ddev/config.yaml. `ddev start`, import a db, export a db. Verify correct behavior. 
    * Make a snapshot, `ddev snapshot --name=10.1snapshot`
    * `ddev rm` and set back to 10.2 with `ddev config --mariadb-version=10.2`. 
    * `ddev start`. `ddev logs -s db` should show that an upgrade happened successfully.
    * `ddev snapshot --name=10.2snapshot`
    * Try to restore the 10.1 snapshot. It should complain.
    * Now `ddev config --mariadb-version=10.1` again and start. It should fail and complain because it has 10.2 db.
    * BuT you should be able to `ddev restore-snapshot 10.1snapshot` and have it come up.
    * Then try `ddev restore-snapshot 10.2snapshot`. It should complain that it can't do that.
    * Remove the config before continuing.
2. **PHP 7.3**:
    * Configure php 7.3 with `ddev config --php-version=7.3` and `ddev start`
    * `ddev ssh` and verify that `php --version` is as expected
    * On a Drupal 8 project visit admin/reports/status/php to verify. (or use phpinfo.php)
3. **Webcaching**:
    * On macOS only, edit config.yaml for `webcache_enabled: true` and `ddev start`.
    * Visit the site. Install a site. It's so fast. Verify that file contents are as expected both on host and in container after you create content using the web project and after you create a file on the host.
    * Use `ddev list` and `ddev describe` to verify syncing status, use `ddev logs -s bgsync -f to see it in a window while you work.
    * Use `ddev composer create` and other `ddev composer` commands, verify correct behavior. And super-important: Make sure that the contents (created in the container) appear properly on the host.
    * Verify that `webcache_enabled: true` is unacceptable option on windows/linux 
4. Symlinks (Windows 10 Pro with Docker for Windows only)
    * Start with developer mode *off* on your Windows machine.
    * Start a project.
    * Create a few random symlinks inside the container. They should be valid symlinks. (but are actually XSym files)
    * Use `ddev composer require` to start something up, maybe `ddev composer require sebastian/version`. You should see it complain that it can't fix the symlinks.
    * Now enable developer mode.
    * Repeat the steps above to verify that you now get a prompt "Replaced these simulated symlinks" that corresponds to symlinks you create.
    * Use `ddev composer create`  to create a nontrivial TYPO3 project. OP's https://github.com/HofUniversityIndieOne2018/red-cross-project is a good one to use. (Or check it out and `composer install` it.) There are key symlinks in web/typo3conf/ext that should be replaced with real symlinks.
5. Sentry instrumentation:
    * Verify that actions you take are reported on sentry.io. If you need a login we'll get you in there.
    * Verify that request to opt-in happens at the correct time (new release, or first-ever)
6. Global configuration
    * Verify that you can use `ddev config global` to set various items
    * Verify that you can set global configuration for omit_containers on dba and/or ssh-agent and get the correct result.
7. Post-start hook only runs when container is actually recreated.
    * Create a post-start hook. It can just be `exec bash -c "echo hi there"`
    * Verify that it gets executed on `ddev start`
    * Do another `ddev start` without changing anything. The hook should not fire.
    * Change something like php version and `ddev start`. The hook should fire.
    * `ddev rm` && `ddev start`: The hook should fire.
    * `ddev restart`: The hook should *not* fire.
8. ddev-ui: Take a little spin with the released ddev-ui to make sure it works with this version of ddev.
9. uploadprogress: Use apache-fpm and visit the admin/reports/status page of any Drupal project. You should see that uploadprogress is enabled and functioning.
10. Multiple ssh-keys of various types: See the manual testing instructions in https://github.com/drud/ddev/pull/1295 to create keys and then authenticate with them. Do this with the keys both in the ~/.ssh directory and also in a random directory for use with `ddev auth ssh -d <dir>`
11. ddev-router not restarting all the time:
    * Start project1 and project2
    * `ddev rm` project1 and then `ddev start` it. The ddev-router should not stop or start or be recreated.
    * Change the http port for project1 and `ddev stop` and `ddev start`. The router should be recreated to accommodate the changed port.
    * `ddev rm -a` and the router should go down with the last project.
12. Wordpress in a subdirectory:
    * ddev composer create wordpress/skeleton and make it work. See packagist (https://packagist.org/packages/wordpress/skeleton) and github repo https://github.com/ttskch/WordPress.Skeleton
    * Install bedrock, see https://roots.io/bedrock/
13. _apt user back in web container:
    * Use a post-start hook to install a debian/ubuntu package.  See (example: https://ddev.readthedocs.io/en/latest/users/extending-commands/#adding-additional-php-modules-example) - Make sure it results in no errors when you start.
14. Verify `ddev config` and friends in subdirectory (https://github.com/drud/ddev/issues/1158)
    * Use `ddev config` in a subdirectory of an existing project, like in `sites/default` on a Drupal project. Verify that it updates the main config.yaml rather than creating a new one.
    * Use `ddev ssh` in a subdirectory on Windows, make sure it behaves correctly.
15. Path accessed by another name problem https://github.com/drud/ddev/pull/1324
    * On a mac, create a project named "junk" in a directory named "junk". Start it.
    * cd into the same directory, but using `cd ../JUNK`. `ddev start` or whatever. You should not get an error.
    * Use a symlink to the junk directory and cd into that symlink. `ddev start` there should also work.
    * Create a project somewhere else named junk and start it. You should get an error.
16. `ddev list --continuous`
    * Run `ddev list --continuous` in a window while doing lots of things (maybe things above). It should survive anything. No panics please.
    * `ddev auth ssh` from Powershell on Windows: See if it works. It should.

**Comment by andrewfrench** [comment]
1. MariaDB 10.1 support 
`ddev config —mariadb-version 10.1` successfully sets the config value  `ddev exec mariah —version` => 10.1.37  

2. php7.3 support
` ddev config --php-version 7.3 `
`ddev exec php --version` shows 7.3

 TYPO3 System Information window shows PHP v7.3.0-1

3. webcache
 TYPO3 installation works well, had to wait a moment for cache to sync before `ddev config` would succeed, and used `ddev exec touch public/FIRST_INSTALL` to initiate the installation process  due to an intermittent webcache issue recorded in #1339 

Drupal8 Umami installation is super-fast, a small delay for cache to catch up.  
`ddev logs -s bgsync -f` outputs continuous log information .

4. Windows Symlinks 

5. Sentry Instrumentation 
No ~/.ddev/global_config.yaml: asked for permission 
Set last_used_version to 1.0.0: asked for permission
 Deleted global config and used other commands, including implicit starts: did not ask (assumed opt-out)
  After opting in, failing command is sent to Sentry: `ddev start does-not-exist` 

6. Global configuration
 ` --omit-containers` and `--nistrumentation-opt-in` both correctly set config values through `ddev config global`  

Both dba and ddev-ssh-agent containers can be omitted 

7. post-start hook 
Hook fires on a first `ddev start` 
Hook does not fire on second `ddev start`
 Hook fires on `ddev rm && ddev start`
 Hook does not fire on `ddev restart` 

8. ddev-ui 

9. With apache-fpm and Drupal 8, Upload Progress is enabled. 

10. Created the following keys, which were added on `ddev auth ssh`:
```
 Identity added: /home/.ssh/delete_dsa (/home/.ssh/delete_dsa)
 Identity added: /home/.ssh/delete_ed25519 (andrew@narwhal)
 Identity added: /home/.ssh/delete_rsa (/home/.ssh/delete_rsa) 
Identity added: /home/.ssh/id_rsa (/home/.ssh/id_rsa) 
```

11. ddev router restarts
 ddev router is up to date (not restarted) when a projects is rm-ed and started 
ddev route is restarted when project HTTP port is changed then started  

12. WordPress-in-the-subdirectory 
`ddev config —project-type php`
 `ddev start` 
`ddev composer create wordpress/skeleton` 
`ddev config —project-type wordpress —docroot wp` 
`ddev start`

13. Apt 
```
hooks:
  post-start:
    - exec: sudo apt-get update && sudo apt-get install ruby
```
(successful )

14. Config in a subdirectory 
`cd project/`
 `ddev config --show-config-location` 
`mkdir -p some/dir/here`
 `cd some/dir/here`
 `ddev config --show-config-location`
 `ddev config --project-name my-new-project-name` 
15. Path accessed by another name 
`cd Project`
 `ddev config --project-type php` 
`ddev start`
 `cd ../pROJECT` 
`ddev start` => no error   
`ln -s ./Project ./PRJ`
` cd ./PRJ ddev start  `
`mkdir ~/anotherdir/Project`
` cd ~/anotherdir/Project `
`ddev start` => error 

16. `ddev list --continuous`
 Ran for ~an hour over multiple operations, no panics 

17.

**Comment by rfay** [comment]
Worked through the test plan today testing 1e687a79b5104409fda861d08689c4ec608b8757 (bump containers), mostly on Windows 10 Pro/Docker-for-Windows. 

1. (Mariadb 10.1): Used composer to create a TYPO3 v8. `ddev config --php-verison=7.1 --mariadb-version=10.1`, then `ddev composer create typo3/cms-base-distribution  ^8 --no-interaction --no-dev --prefer- dist` - Everything seemed to have worked ok.

2. php 7.3: Worked fine; did it in a php-type project with php-version=7.3

3. Webcaching (tried on Windows, OK, but needed to chmod sites/default/files, etc. Same old thing. Might be adequate. TODO

4. Symlinks: Worked with dev mode on, complained with it off. (Couldn't figure out how to install red-cross-project). Manual creation of links worked.

5. Sentry (I let Monica do this one)

6. ddev config global - works fine.

7. Post-start hook: Works fine, actually works right when you create a new hook and `ddev start`

8. ddev-ui: Most functionality seemed like it worked the same as the other day.

9. Uploadprogress: Working perfectly. On d8 it also works with nginx-fpm.

10. multiple key ssh auth: Everything worked fine. 

11. Router restart: Passed fine.

12. Wordpress in subdir: I think Andrew and Monica got this better than I did.

13. apt success: Working fine

14. ddev config in subdirectory, ddev ssh in subdir: All worked perfectly.

15. Path accessed by another name: Worked fine.

16. ddev list --continuous running a lot on several windows mac and windows.

17. ddev auth ssh from PS works fine.

**Comment by rfay** [comment]
IMO unless Monica comes up with a late fail we're good to release tomorrow. Andrew will probably do it in the morning, or else we'll do it in the afternoon.

We did discover some not-unexpected issues with the webcache feature - Andrew created #1339 about webcache stopping caching, and we were able to recreate it. Apparently a huge deletion on the host side (at least that's where we know how to do it)  can end up with unison not working. We don't actually have a clue why this is.

**Comment by mafriend** [comment]
Hey folks! 

Here's my testing notes for the latest local release as well as UI regression testing:
local notes: https://cl.ly/3f0f4fe87020
UI notes: https://cl.ly/727c47d9bfbb

There were a few hiccups on my end, but nothing that I think should hold up a release. Good work everyone! 🍰 🍾 🎈
