### ISSUE TITLE
v1.5.2 Release Checklist Due 2019-01-15

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1343]
Remaining actions:

- [x] Review release (product owner)
- [x] Approve release (product owner and release manager)
- [x] Create binaries (any DRUD maintainer)
- [x] Draft release notes (release manager)
- [x] Coordinate announcements for blog, newsletter, etc with marketing (product owner)
- [x] Create release (release manager)
- [ ] Update Roadmap (TPM/release manager)
- [ ] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
# Release Notes for ddev v1.5.2:

# Installation/Upgrade
See the [installation instructions](https://ddev.readthedocs.io/en/stable/#installation) for details, but it's easy:
- macOS Homebrew and Linux Linuxbrew: `brew upgrade ddev`
- Linux or macOS via script:
`curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash`
- Windows: Download the ddev_windows_installer.v1.5.2.exe above.
And anywhere, you can just download the tarball or zipball, untar or unzip it, and place the executable in your path where it belongs.
# Key changes in v1.5.2:
* [Linuxbrew](http://linuxbrew.sh/) becomes our preferred install/upgrade technique on all Linux distributions. 
* PHP 7.3 now has php-memcached in web container
* ghostscript added to web container
* php-apcu added to web container, significant performance boost. For Drupal 8 `$settings['class_loader_auto_detect'] = FALSE;` is added to the settings.ddev.php and it increases performance quite a lot with php-apcu. Thanks to @mglaman for the suggestion in [Stack Overflow](https://stackoverflow.com/a/54049172/215713) 

# Commits since v1.5.1
baa15bf2 (upstream/master) Web container maintenance, fixes #1350, fixes #920, fixes #1337 (#1368)
9c0a8ed8 Documentation updates including for Docker Toolbox, fixes #1271 (#1370)
e559fa0c Use pv to show progress bar during import-db (#1349)
76187c45 Document how to add a beanstalk queue (#1315)
9116c735 Fix Arch Linux docs link (#1366)

**Comment by rfay** [comment]
Release candidate artifacts are at https://circleci.com/gh/drud/ddev/8492#artifacts/containers/0

**Comment by andrewfrench** [comment]
### v1.5.2 Testing

**Install on Linux via Linuxbrew, see [docs](https://ddev.readthedocs.io/en/latest/#homebrew-macos), verify behavior**

On Ubuntu 18.04 (VM)

```
$ brew uninstall -f ddev
$ brew tap rfay/ddev
$ brew install rfay/ddev/ddev

$ ddev version
v1.5.1 (previous version at rfay/ddev)
```

✅ ddev is installable on Linux through Linuxbrew, currently the previous version until this version is released.

**Install on macOS using brew. Important because we have a whole new formula**

```
$ brew uninstall -f ddev
$ brew tap rfay/ddev
$ brew install rfay/ddev/ddev

$ ddev version
v1.5.1 (previous version at rfay/ddev)
```

✅ ddev is installable on MacOS through Homebrew, currently the previous version until this version is released.

**Build from source on macOS, `brew install --build-from-source` ddev**

```
$ brew uninstall -f ddev 
$ brew tap rfay/ddev
$ brew install --build-from-source rfay/ddev/ddev

$ ddev version
v1.5.1 (previous version at rfay/ddev)
```

✅ ddev is buildable from source (when Docker is running)

**Make sure that ddev snapshot and restore-snapshot works on all platforms, especially docker-toolbox**


**Verify ghostscript (gs) exists in web container. For extra credit, use it in a Typo3 v9 install (see [issue instructions](https://github.com/drud/ddev/pull/1368#issuecomment-452218690))**

```
host $ ddev start
host $ ddev ssh 
web-container $ gs

GPL Ghostscript 9.26 (2018-11-20)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
GS>
```

✅ Ghostscript 9.26 is installed on the web container 

**Verify php-apcu and php-memcached  in web container (admin/reports/status/php on Drupal, or  `php -i`. php-memcached, use php 7.3**

```
host $ ddev config --php-version 7.3
host $ ddev start 
host $ ddev ssh 
web-container $ php -i | grep apcu
/etc/php/7.3/cli/conf.d/20-apcu.ini,
apcu

web-container $ php -i | grep memcached
/etc/php/7.3/cli/conf.d/25-memcached.ini
memcached

(several memcached config lines...)

**Comment by andrewfrench** [comment]
Whoops, my bad! I'll re-test those points and update with the results.

**Comment by mafriend** [comment]
Hey folks!

Here are my synthesized testing notes thus far: 
**MacOS**
* Install on macOS using brew. Important because we have a whole new formula. ✅
** Heads up, I did notice an error pop up when installing via brew regarding docker, but the install successfully completed. I removed everything and installed again and no error occurred! It could have been a blip in my internet that caused the error? 
* Build from source on macOS, brew install --build-from-source ddev ✅
* Make sure that ddev snapshot and restore-snapshot works on all platforms, especially docker-toolbox. ✅
* Verify ghostscript (gs) exists in web container. For extra credit, use it in a Typo3 v9 install (see issue instructions) ✅
* Verify php-apcu and php-memcached in web container (admin/reports/status/php on Drupal, or php -i. php-memcached, use php 7.3. ✅

I am going to run through this on windows 10 home now and will leave my notes when testing has been completed!

**Comment by rfay** [comment]
Docker toolbox on Windows 10 Home, macOS, and Manjaro Linux testing
* Install d6lts with custom php and mysql settings.  Verified that the php and mysql settings happened.
* Manjaro linux (arch linux derivative): `brew untap rfay/ddev && brew tap drud/ddev && brew install ddev. Then `ddev composer install` on a D8 project and visited the site.
* brew uninstall ddev && brew install ddev on macOS: Successful v1.5.1.
* macOS build-from-source: brew uninstall ddev; brew untap rfay/ddev; brew tap drud/ddev; brew install --build-from-source ddev. Stuttered on inability to install docker (which is a build-time dependency) because docker is already installed another way.  But v1.5.1 worked ok after build.
* Manjaro linux: `brew uninstall ddev && brew install --build-from-source ddev` worked. It needed to have docker already running, so the docker dependency was not the complete picture. 
* d6lts project on docker toolbox: `ddev snapshot --name=base`; `ddev rm -RO`; `ddev start`; ddev restore-snapshot base; Worked fine, got me back where I started.
* TYPO3 v9 install via `ddev composer create` on Manjaro Linux and Docker Toolbox/Win10 Home. 
* Verify gs in shell: I found gs in shell, also went through TYPO3 environment to see images created successfully.
* Apcu enabled in admin/reports/status/php, php-memcached installed

It all seems to be working to me. I guess what I want to do is run another PR through to test everything on docker 18.09.1 on the testbots. Probably just a simple docs PR.

**Comment by rfay** [comment]
Good enough, released!

**Comment by dclear** [comment]
re-opening to do my cleanup tasks

**Comment by dclear** [comment]
* close milestone, update roadmap wiki, close project, spin up next release issue
