### ISSUE TITLE
v1.5.1 Release Checklist Due 2019-01-03

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1365]
Remaining actions:

- [ ] Review release (product owner)
- [ ] Approve release (product owner and release manager)
- [ ] Create binaries (any DRUD maintainer)
- [ ] Draft release notes (release manager)
- [ ] Coordinate announcements for blog, newsletter, etc with marketing (product owner)
- [ ] Create release (release manager)
- [ ] Update Roadmap (TPM/release manager)
- [ ] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
Provisional release notes

v1.5.1 is a minor release to resolve a performance regression; Mostly you should read the [v1.5.0 release notes](https://github.com/drud/ddev/releases/tag/v1.5.0) if upgrading from an earlier release. 

# Installation/Upgrade

See the [installation instructions](https://github.com/drud/ddev/blob/master/docs/index.md) for details, but it's easy:

- macOS Homebrew: `brew upgrade ddev`
- Linux or macOS via script:
`curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash`
- Windows: Download the ddev_windows_installer.v1.5.0.exe above.

And anywhere, you can just download the tarball or zipball, untar or unzip it, and place the executable in your path where it belongs.

# Key changes in v1.5.1:

* A performance regression omitted the docker ":cached" attribute in the docker-compose.yaml. (#1361). That cut performance by 40-50% on normal (non webcache-enabled setups). It probably made no difference if you were using `webcache_enabled: true` 
* In v1.5.0 php 7.3 did not work with apache. (#1351)


# Commits since v1.5.0

**Comment by rfay** [comment]
Test Plan - Edit as needed

1. Performance (without webcache_enabled). 
    * Test D8 install inside container `time drush si -y` should be about 40% faster.
    * Test D8 browser install and record speed. 
    * Experiment with web browsing
    * Verify `ddev composer ...` behavior
2. Behavior (with webcache_enabled)
    * Performance should be the same (fast)
    * Follow syncing with `ddev logs -s bgsync -f` to see that behavior seems correct.
3. Apache with php 7.3 (without webcache_enabled)
     * Configure TYPO3 v9 with php7.3 and apache-fpm
     * Do an install.
     * Click around, create a page, stuff like that.

**Comment by rfay** [comment]
The artifacts in https://circleci.com/gh/drud/ddev/8182#artifacts/containers/0 should be representative for testing this release. 

Beyond belief, but the 'dirty' marker on those artifacts means I still haven't mastered the .gitattributes problem.

**Comment by andrewfrench** [comment]
## Performance (👍)
- Get project via composer
`ddev composer create drupal-composer/drupal-project:8.x-dev`

- D8 install inside container 
`time drush si -y`
`0m41s`

- D8 browser standard installation
`~1m30s`

- Browsing through site showed no noticeable performance or latency issues

## Behavior with webcache enabled (👍)
- `ddev composer create drupal-composer/drupal-project:8.x-dev` completed quickly

- `ddev logs -s bgsync -f` showed batched syncing as expected

## Apache with php 7.3 (👍)

- Configured a project with PHP7.3 and apache-fpm
- `ddev composer create typo3/base-cms-distribution ^9`
- Installed TYPO3
- Clicked through backend, responsive as expected

**Comment by mafriend** [comment]
Hey folks! I don't want to hold you up on this small release, but I'm held up for the next few hours in meetings and dont think ill be able to run through all of the scenarios. Since I'm running on a macOS right now and Andrew has also hit Mac and being that this is a small release, the risk of this deploy causing issues is pretty low! 

Here's what I was able to hit during my testing:
1. Verify DDEV composer functionality ✔️ 
2. Test D8 browser install and record speed (with web browser experimentation) `~2m` ✔️ 
- Note: I am currently on a public wifi with speeds at about 160mbps
3. Test D8 install inside container `time drush si -y` should be about 40% faster `~1m10s` ✔️ 

@rfay, are these times okay? They seem a little bit longer, but I am currently on public wifi which might be causing the delay! 

Thanks!

**Comment by rfay** [comment]
That's fine, thanks @mafriend  - Wifi wouldn't affect any of that anyway.

**Comment by rfay** [comment]
v1.5.1 is released and announced.
