### ISSUE TITLE
v1.8.0 Release Checklist Due 2019-05-14

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1533]
Remaining actions:

- [x] Review release (product owner)
- [x] Approve release (product owner and release manager)
- [x] Create binaries (any DRUD maintainer)
- [x] Draft release notes (release manager)
- [x] Coordinate announcements for blog, newsletter, etc with marketing (product owner)
- [x] Create release (release manager)
- [ ] Update Roadmap (TPM/release manager)
- [x] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
# Draft Release Notes for v1.8.0

# Installation/Upgrade
See the [installation instructions](https://ddev.readthedocs.io/en/stable/#installation) for details, but it's easy:
- macOS Homebrew and Linux Linuxbrew: `brew upgrade ddev`
- Linux or macOS via script:
`curl https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash`
- Windows: Download the ddev_windows_installer.v1.7.1.exe above or with Chocolatey `choco install ddev` or `choco upgrade ddev` (or `choco install ddev --version=1.7.1` while it's in the approval process.)
And anywhere, you can just download the tarball or zipball, untar or unzip it, and place the executable in your path where it belongs.


# Key changes in v1.7.1:

* config.*.yaml overrides: local configuration files can be used to override a team-standard checked-in .ddev/config.yaml. See [docs](https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#extending-configyaml-with-custom-configyaml-files).  #1504 and #1410.
* Optional static bind ports for db and webserver containers. Those who want the dbserver or webserver bound port to be static within a project can use `host_db_port` or `host_webserver_port` to specify it: #1502, #1491, #941  
- Previous versions of Docker for Mac supported operating systems back to El Capitan, but Docker-for-Mac has dropped support for anything before macOS Sierra 10.12, so ddev also has to drop support for everything before Sierra.
- The default PHP version changes to 7.2. This affects new Drupal 8 and Drupal 7 projects, as well as projects of type "php".
* Fix regression in v1.5.0 where mariadb_version = 10.1 did not properly set the container version to the 10.1 container version.
* The ddev-dbserver images now use the official MariaDB docker image (which uses Debian) as a base, instead of building a custom Alpine image. This *should* be invisible to all users, but we love to hear feedback.

# Thanks!

Many community members helped out with this release. 

And the amazing [mkcert](https://github.com/FiloSottile/mkcert) from @FiloSottile made the seemingly impossible task of trusted local development certificates *possible*. Thanks! Is open source great or what?

# Commits since v1.7.1

- composer cache moves (delete old one)?
- switch to start/pause/stop
- volumes for service storage?
- SSL support, several places
- Explain requirement of mkcert, how to install and initialize
- custom nginx configs may be out of date, not include SSL; this may not be important
- NGINX configuration reorganized, now can add snippet in .ddev/nginx
- Exposed https port on localhost
- Write about how much mkcert meant to this, open source hurray!
- `ddev config --host-https-port`
- https port first in `ddev list` and `ddev describe`
- New extension capability with extra packages etc.
- Exec is interpreted by bash. Have to remove existing "bash -c"
- ddev exec allows tty interaction. `ddev exec mysql`, `ddev exec drush sqlc`
- Nginx snippets, instead of whole file

**Comment by rfay** [comment]
# Test Plan for v1.8.0

* New packages: Use phpinfo.php or Drupal admin/reports/status/php to verify that the pgsql and blackfire.io packages are in there.
* Wordpress composer recipe: Verify correctness of docs for [wordpress composer install](https://ddev.readthedocs.io/en/latest/users/cli-usage/#wordpress-quickstart)
*

**Comment by jonaseberle** [comment]
1. ok
2. did not check
3. ok
4. ok (also verified pause vs. stop which have not used before) - I still think a new command `remove-data` would be favorable.
`ddev help stop` has a little formatting error:
`Stop and remove the containers of a project. You can run 'ddev stp['
from a project directory to stop/remove that project, or you can stop/remove projects in` ...
Btw: For people not used to docker containers `stop` IS de facto a destructive operation as changed files outside of volumes WILL be gone. 
5. ok
6.
7.
8.
9.
10.
11.
12.
13.
14.
15.

**Comment by rfay** [comment]
Randy's testing:
## Concerns
* Should blackfire.io be disabled by default?

**Comment by mglaman** [comment]
@rfay Blackfire shouldn't cause any performance problems idling in the background.

> Blackfire profiles are generated only for requests triggered by a Blackfire user, or by Blackfire when profiling is automated. That is made possible thanks to our runtime instrumentation. As no other requests will be instrumented, Blackfire will add no overhead for your end users, which makes it safe to use in production. 

I have the Blackfire extension installed in production on plenty of projects. The _only_ think I could think of is it someone installed Tideways or XHProf? But even then all of these runtimes only trigger when invoked. I've had XHProf and Blackfire on a site at the same time without errors.

**Comment by andrewfrench** [comment]
Test notes:

1. Did not test

2. **WordPress Composer recipe:** 👍 
I was able to use the recipe documentation to start a fresh WordPress project using Composer, but I did hit the `ddev config` speed bump.

3. **PHP Quickstart:** 👍 
An important addition to the documentation. I followed the steps to create a very simple project.

4. **Reorganize start/pause/stop:** ⚠️ 
I'm able to control the container lifecycle using start, pause, and stop instead of start, stop, and remove. I love the symmetry of start vs. stop, and pause is a natural addition to the command set. There is a typo in the `Long:` help text for `ddev stop`: `You can run 'ddev stp['...`

5. **Additional hostnames/FQDNs resolution:** :+1:
All additional hostnames and FQDNs defined in .ddev/config.yaml are recognized in-container, both for http and https.

6. Did not test

7. **Trusting local certs:** 👍 
After configuring, the https local sites are trusted by the browser.

8. **Additional packages:** 👍 
I'm able to define additional packages to be installed in a container. After starting or restarting containers, the packages are installed, as confirmed by `ddev ssh`.

9. **Custom containers:** 👍 
Similarly, I'm able to define a custom container image for web and db containers. The expected packages are installed and other RUN steps are executed.

10. **Interactive `ddev exec`:** 👍 
I'm able to interactively run commands in-container through `ddev exec`, e.g. `ddev exec vim myfile.txt`. This is very cool!

11. **Bash interpretation in `ddev exec`:** 👍 
My go-to test command for this is `ddev exec curl https://drud.com | tee drud.com.tmp`. This works just as it would in a normal Bash context, and the contents of the resulting file is confirmed by `ddev exec cat drud.com.tmp`.

12. **Bash interpretation in hooks:** 👍 
This was tested using the same command in **11.** and was successful.

13. **Rework config-in-subdirectory:** 👍 
When a .ddev/config.yaml exists in a parent directory, `ddev config` warns the user of the existing config, but continuing creates a new config in the current working directory.

14. **`ddev composer ... --no-interaction` still requires confirmation:** 👍 
Despite the `--no-interaction` flag, the 'delete everything' step requires information.

15. Did not test

There are *a ton* of really major updates here &mdash; this is probably one of the biggest and best ddev updates yet!

**Comment by hebbet** [comment]
hi, i tested the rc on windows 10. 

i ran mkcert --install, but chrome doesn't recognize the CA, also the CA is listed in the trust store.

**Comment by rfay** [comment]
Hi @hebbet - I've tested this a number of times on WIndows 10 with Chrome. Could you recheck that you:

* `ddev remove --all` before starting (so that there is no router running and the router gets recreated)
* Restarted Chrome

Thanks for testing, and thanks for reporting. Hoping to understand this better.

**Comment by rfay** [comment]
This is all done, and I even went through Stack Overflow ddev articles looking for things that needed to be updated (bash -c, etc). 

Elli and I are working on announcements and other communication.

**Comment by dclear** [comment]
close project board, milestone, update releases wiki page
