### ISSUE TITLE
v1.10 Release Checklist Due 2019-07-24

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1669]
Remaining actions:

- [ ] Review release (product owner)
- [ ] Approve release (product owner and release manager)
- [ ] Create binaries (any DRUD maintainer)
- [ ] Draft release notes (release manager)
- [ ] Coordinate announcements for blog, newsletter, etc with marketing (product owner)
- [ ] Create release (release manager)
- [ ] Update Roadmap (TPM/release manager)
- [ ] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
## Test plan for ddev v1.10.0

Current binaries can be installed as described in https://github.com/drud/ddev/releases/tag/v1.10.0-rc1, available on the homebrew ddev-edge channel, etc.

Please report your results below (if minor/tiny or just affirmation) or in issues is anything found that needs to be fixed.

1. **Custom commands**. (See [docs](https://ddev.readthedocs.io/en/latest/users/extend/custom-commands/))
    - Try out `ddev mysql`
    - Create your own in-container command
    - Create your own host command
    - Try out the example commands `ddev mysqldump` and  `ddev mysqlworkbench` (not perfect, but I think because mysqlworkbench isn't perfect)
    - Try command when project is not running, it should respond correctly by starting the command.
2. **Real user in container**
    - `ddev ssh` and review the environment you have. Username? UID? Hostname?
    - Make sure `ddev auth ssh` works properly and gives you access in the web container to ssh credentials.
3. **ddev poweroff**
    - Try `ddev poweroff` with projects running, paused, or stopped. Make sure it does what you expect. No ddev containers should be running (or stopped) afterward. Use `docker ps -a` to verify.
4. **ddev delete**
    - Try `ddev delete proj1 proj2`: It should properly warn you about what it's trying to do, and then do it. Verify that volumes are gone with `docker volume ls | grep proj1`
    - Try with `—omit-snapshot` to see behavior
    - Try `ddev delete images`, which should delete lots of extraneous images.
5. **User files in home directory** ([docs](https://ddev.readthedocs.io/en/latest/users/extend/in-container-configuration/))
    - Add a .ssh/config (in .ddev/homeadditions/.ssh/config), verify that it gets copied into the container
    - Add a bash alias in .ddev/homeadditions/.bash_aliases, then `ddev start` and `ddev ssh` should have that alias.
6. **host_db_port validation (known bug in v1.10.0-rc1)**
    - `host_db_port: 59002` with `ddev start` should result in the db port being 59002. `ddev describe` should show it that way. And you should be able to use the mysql command provided in `ddev describe` to access it on 59002.
    - Validate that host_webserver_port and host_https_port are also working correctly
7. **`ddev ssh` uses bash login shell**
    - When you `ddev ssh` the .profile should be executed. Add an echo to the in-container .profile to validate.
8. **Signed windows and macOS binaries**:
    - On Windows, in file explorer, right click on both `ddev_windows_installer.*.exe` and `ddev.exe` and look at the certificates tab to validate correct signing.
    - On macOS, use `codesign -dv --verbose 4 </path/to/ddev` to verify signing.
9. `ddev describe` and `ddev start` URL formatting
    - `ddev describe` should show ALL urls for the project, both http and https. There should be no commas in the output (tabular format)
    - `ddev start` still shows only the https (if mkcert installed) URLs, but there should be no commas attached to or interspersed in the list.
10. `ddev restart` improvements:
    - `ddev restart -a` or `ddev restart --all` should restart all projects shown in `ddev list`
    - `ddev restart proj1 proj2 proj3` same.
11. `ddev ssh <projectname>` should work from any directory, if the project is running.
12. `ddev import-db` accepts stdin
    - `gzip -dc yourdb.sql.gz | ddev import-db`
    - `gzip -dc yourdb.sql.gz | mysql db`
13. **ddev exec accepts stdin**:
    - `echo "hi there" | ddev exec cat`
    - `echo "hi there" | ddev exec "cat >/tmp/junk.txt"` and `ddev ssh` and `cat /tmp/junk.txt` to see that it went into the container and was captured there.
14. **PHPMyAdmin and Router ports no longer shared on all interfaces**
    - `ddev start` and then use telnet or nc to try to access the main ports (80, 443, 8025, 8036) on network interfaces other than localhost.
    - Alternately, try to access those ports over the network from another computer (or VM)
15. Review healthcheck usage. 
    - Look at `docker events`, you should see far less than previously.An interesting tool is `docker inspect ddev-router | jq ".[].State.Health"`, which shows the last few healthchecks and their result (change container name as necessary). This is particularly interesting early in the life of a container.
16. **ddev import-db no longer drops all tables**
    - Use `ddev import-db` to import from a dump that has only a single table (and no DROP). The data should be added to the table.
17. **TYPO3 installer improvements with https**
    - Install TYPO3 using http, it should work as normally.
    - (You can clean up and try an install again by removing typo3conf/LocalConfiguration.php, typo3conf/PackageStates.ph, and typo3temp)
    - Install TYPO3 using https. It will probably fail at this point with a 500 error. See [docs](https://ddev.readthedocs.io/en/latest/users/cli-usage/#typo3-quickstart). Verify doc validity.
    - Install TYPO3 using https but with TYPO3 [patch](https://review.typo3.org/c/Packages/TYPO3.CMS/+/61374). (requires git-based TYPO3).  Should work perfectly.
18. **TYPO3 image creation**
    - Verify that TYPO3 image creation works correctly in the image testing area.
19. **Drush backdrop extensions to v1.0.0**
    - Make sure the drush backdrop extensions in the container are v1.0.0, and try something new on a backdrop project that needs v1.0.0
20. **ddev ssh** should not return error message after error in container.
    - `ddev ssh` and then create an error (type nonsense or just type "false"). When you exit (with `exit` or <ctrl-d>, no error should be reported.

**Comment by rfay** [comment]
Test results, mostly on Windows, using 2.1.0.0 docker desktop. There are 3 outstanding issues discovered.

1. **Custom commands**. 

    👍 ddev mysql works

    👍 Created a db container "junk" command, worked fine. Example even worked.

    👍 Created host command "junkhost". Worked fine.

    👍mysqldump worked fine. 👍mysqlworkbench worked fine; had to do new install. It's hard to find your way to the "schema" tab below on Windows.

    👍 ddev mysql when not running started the project and then ran the command.

2. 👍 **Real user in container**

    👍 User and hostname are in there. On Windows we use uid 1000 always:

        uid=1000(rfay) gid=1000(rfay) groups=1000(rfay)
        rfay@t3git-web:/var/www/html$ hostname
        t3git-web

    👍 `ddev auth ssh` worked still and auth into external host worked.

3. 👍 **ddev poweroff**
4. 👍 **ddev delete**
    - 👍`ddev delete t3v9 t3test` started both projects, took a snapshot, then removed them completely, and the docker volumes were gone.
    - 👍with `—omit-snapshot` it skipped the snapshot; with `--omit-snapshot -y` it didn't ask for confirma
    - 👍`ddev delete images`, actually seems to have done exactly the right thing. bgsync images remained, but those aren't included since it's deprecated.
5. 👍 **User files in home directory** ([docs](https://ddev.readthedocs.io/en/latest/users/extend/in-container-configuration/))
    - 👍 Added a .ssh/config, did `ddev restart`, and the Host I added worked fine

            Host webh
            HostName [webhosting.](http://webhosting.thefays.us/)example.com
            User xxx

    - 👍 Added a .gitconfig with my own git email and name, after `ddev restart` it worked fine. I was confused at first because I tried just `ddev start` and since the project was running, the start script on the container didn't get run.
    - 👍 Add a bash alias- I just `ln -s bash_aliases.example .bash_aliases` then `ddev start` and `ddev ssh` and then the `ll` alias worked fine.
6. h**ost_db_port validation (known bug in v1.10.0-rc1) [#1747](https://github.com/drud/ddev/issues/1747)**
    - `host_db_port: 59002` with `ddev start` should result in the db port being 59002. `ddev describe` should show it that way. And you should be able to use the mysql command provided in `ddev describe` to access it on 59002.
    - Validate that host_webserver_port and host_https_port are also working correctly
7. ✔ **`ddev ssh` uses bash login shell**
8. 👎 **Signed windows and macOS binaries**:

    ✔ On Windows, in file explorer, right click on both `ddev_windows_installer.*.exe` and `ddev.exe` and look at the certificates tab to validate correct signing.

    👎 On macOS, use `codesign -dv --verbose 4 </path/to/ddev` : Apparently neither v1.10.0-alpha4 nor v1.10.0-rc1 got signed successfully. [#1750](https://github.com/drud/ddev/issues/1750)

9. ✔`ddev describe` and `ddev start` URL formatting. I like the additional information that is provided, but am not completely thrilled about the formatting, and the fact that it can scroll past my window. http and https urls are provided, which is correct.
10. ✔`ddev restart`
11. ✔`ddev ssh <projectname>` works from anywhere.
12. ✔ `ddev import-db` accepts stdin
13. ✔ **ddev exec accepts stdin**:
14. ✔ **PHPMyAdmin and Router ports no longer shared on all interfaces**
15. ✔ Review healthcheck usage. `docker events` shows a far calmer event situation; with a single project running, you see the web and db containers and router healthcheck fire periodically, but it's far less than earlier. I would imagine we could dial it back more though.
16. ✔**ddev import-db no longer drops all tables:** `delete from users;` and then import-db of a sql that contains only users populates the users table (which still exists, but empty), and leaves all the other tables alone**.**
17. ✔ **TYPO3 installer improvements with https:** 
    - TYPO3 installs fine with http
    - If installation tried with https, it fails with 500 error unless there's already a LocalConfiguration.php there.  Works OK if there's a LocalConfiguration.
    - Installs perfectly under https with [patch](https://review.typo3.org/c/Packages/TYPO3.CMS/+/61374).
18. ✔ **TYPO3 image creation:** The "Image processing" test under "Environment" shows all good generated images.
19. ✔**Drush backdrop extensions to v1.0.0:** `drush backdrop-user-create` worked fine.
20. ✔ **ddev ssh** should not return error message after error in container.
21. 👎 Release creation with BUILD_IMAGE_TARBALLS=true didn't work because it tries to use linux executable in macOS environment.  [#1749](https://github.com/drud/ddev/issues/1749)

**Comment by rfay** [comment]
I think the 3 discovered issues are now taken care of, so after the DDEV_HOST_DB_PORT one is merged and tested, I'll be about ready to do the release of 

@kaystrobach discovered an interesting behavior in #1753; he had a pinned dbimage, and it broke because that image had a full /etc/group. As mentioned in https://github.com/drud/ddev/issues/1753, I think we would do well to improve our detection of situations like this. But I don't think it would be appropriate to do that for this release, because we could introduce other issues.

**Comment by rfay** [comment]
This was completed.
