### ISSUE TITLE
v1.11 Release Checklist

### ISSUE THREAD

**Issue by dclear** [drud/ddev#1755]
Remaining actions:

- [x] Review release (product owner)
- [x] Approve release (product owner and release manager)
- [x] Create binaries (any DRUD maintainer)
- [x] Draft release notes (release manager)
- [ ] Coordinate announcements for blog, newsletter, etc with marketing (product owner)
- [x] Create release (release manager)
- [x] Update Roadmap (TPM/release manager)
- [x] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
# Test Plan for v1.10.0

Artifacts are at 

1. **router_bind_all_interfaces global_config.yaml option**: ([docs](https://ddev.readthedocs.io/en/latest/users/extend/config_yaml/)) 
    - Make sure that with the default configuration (`router_bind_all_interfaces: false`) that ddev sites are available *only* on localhost. You can do this with curl and curl port 80/443 on each IP address.
    - Make sure that with `router_bind_all_interfaces: false` that projects are available on all interfaces. Use curl. Best test is to put something up on the internet or in another place on local network and see if it's accessible. This may require firewall configuration, of course.
2. **docs review**: There are a number of updated docs. Please read at least 
    - [config.yaml and global_config.yaml options](https://ddev.readthedocs.io/en/latest/users/extend/config_yaml/)
    - [FAQ](https://ddev.readthedocs.io/en/latest/users/faq/)
    - [Support](https://github.com/drud/ddev#support)
    - [Favorite commands](https://ddev.readthedocs.io/en/latest/users/cli-usage/#favorite-commands) and [Quick Extra Tools List](https://ddev.readthedocs.io/en/latest/users/cli-usage/#quick-extra-tools-list)
3. **ddev composer create quickstart docs**: Make sure to test Drupal8 and TYPO3 composer installations per the [quickstart docs](https://ddev.readthedocs.io/en/latest/users/cli-usage/#quickstart-guides). TYPO3 should be tested on v10 (master) and v9.
4. **Apache solr docs**: Run through [Apache Solr procedures](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#apache-solr) to verify.
5. **Windows Installer**: Manually verify that the Windows installer downloaded from github release installs everything it says it will. All should show up checked on that last page, and then they should all be installed. Best to use the uninstaller first, make sure everything in c:\Program Files\ddev is gone, then install and make sure sudo and the nfs install script and all are in there.
6. **omit_containers[db]:** Use `omit_containers[db]` per [docs](https://ddev.readthedocs.io/en/latest/users/extend/config_yaml/). This is probably easiest to do with a Drupal project. `ddev start` and verify that only the web container comes up (`docker ps`). Then do an install and accept the defaults for a sqlite3 installation.
7. **ddev composer create flexibility of args**: You should now be able to do almost anything with `ddev composer create` that `composer create-project` allows. Previously it allowed only pre-configured flags, and only a few of them. `ddev composer create -h` has some unusual examples. Try extra flags.
8. **Test ddev on macOS Catalina**: It should work fine. Most important is mkcert usage and trusted https.
9. **Look skeptically at `ddev start` and `ddev list` performance**: How long do they take? `time ddev start`. `time ddev list`. `ddev list` gets worse with more projects configured.
10. `**ddev share` on TYPO3 v9 and v10 projects**: Make sure it works.
11. `ddev powerdown`: Both `ddev powerdown` and `ddev poweroff` should work and they're aliases.
12. **PHP7.4 should be available as PHP version and should work**. Check to see if any of the skipped modules have been updated/provided yet.
13. enable_xdebug and disable_xdebug should work everywhere: Use `ddev exec enable_xdebug` and also `ddev ssh` and then `enable_xdebug`.

**Comment by rfay** [comment]
# rfay testing results

1. ✅ **router_bind_all_interfaces** (mostly). I tested this in a virtual environment, with the project on macOS, and then hit it with web traffic from a Debian 10 VM (Parallels). It behaved as expected when set to true (allowed the traffic) and when set to false (no connection allowed). `ddev config global --router-bind-all-interfaces=true` seemed to work fine and do its job. But I did have one moment where I thought it wasn't working.

**Comment by rfay** [comment]
Released
