### ISSUE TITLE
v0.4 Release Checklist

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#200]
Remaining actions:

* [x] Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [ ] Create release (release manager)

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rickmanelius** [comment]
Updated and will begin the review today alongside https://github.com/drud/ddev/pull/217.

**Comment by rickmanelius** [comment]
Saving a snapshot of my audit thus far (the "rejection" of acceptance is just keeping this accurate until the tests come through as passes).

# ddev v0.4 Review

## Executive Summary

Based on the following analysis, [ddev v0.4](https://github.com/drud/ddev/milestone/4) is NOT YET ready for release.

## Milestone Overview

The intention of ddev v0.4 (see [Roadmap](https://github.com/drud/ddev/wiki/roadmap)) is to make it easy for end-users to get up running quickly. Also, the work to date has largely focused on macOS users and we need a strategy to broaden the scope of this product to include the other major OSs, notably Windows and Linux. To achieve this, we are focusing on the following:

The end-user features specific to ddev v0.4 are as follows:

* Simplified installation script and instructions for macOS
* Decisions on Linux and Windows support
* Upgrade notifications and instructions

In addition to features, we began to address items that will generally support and improve the project, including the following:

* Removing the proxy container if no sites are active.
* Reworking and improving the `ddev list` commmand.
* Enforcing uniqueness of the project name across sites.

## Testing
Performed by Rick Manelius as of 2017-05-12.

### Hardware Setup

I’m using a laptop with the following high level specifications:
* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.12.4

### Software Setup

* Xcode
* Go 1.8.1
* Docker 17.03.1-ce
* Git 2.11.0

### Repositories Used

* [https://github.com/drud/ddev](https://github.com/drud/ddev/commit/8f10148abae794dc42a5740c1cf64fe6bce186d8).

## Results

### Active Testing

* Simplified installation script and instructions for macOS
* Decisions on Linux and Windows support
* Upgrade notifications and instructions
* Removing the proxy container if no sites are active.
* Reworking and improving the `ddev list` commmand.
* Enforcing uniqueness of the project name across sites.

### Works

### Fails

## Decisions
Based on the above manual testing, [ddev v0.4](https://github.com/drud/ddev/milestone/4) is NOT YET ready for release.

## Recommendations

None at this time.

**Comment by rickmanelius** [comment]
Updated Report

# ddev v0.4 Review

## Executive Summary

Based on the following analysis, [ddev v0.4](https://github.com/drud/ddev/milestone/4) is NOT YET ready for release.

## Milestone Overview

The intention of ddev v0.4 (see [Roadmap](https://github.com/drud/ddev/wiki/roadmap)) is to make it easy for end-users to get up running quickly. Also, the work to date has largely focused on macOS users and we need a strategy to broaden the scope of this product to include the other major OSs, notably Windows and Linux. To achieve this, we are focusing on the following:

The end-user features specific to ddev v0.4 are as follows:

* Simplified installation script and instructions for macOS
* Decisions on Linux and Windows support
* Upgrade notifications and instructions

In addition to features, we began to address items that will generally support and improve the project, including the following:

* Removing the proxy container if no sites are active.
* Reworking and improving the `ddev list` commmand.
* Enforcing uniqueness of the project name across sites.

## Testing
Performed by Rick Manelius as of 2017-05-12.

### Hardware Setup

I’m using a laptop with the following high level specifications:
* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.12.4

### Software Setup

* Xcode
* Go 1.8.1
* Docker 17.03.1-ce
* Git 2.11.0

### Repositories Used

* [https://github.com/drud/ddev](https://github.com/drud/ddev/commit/8f10148abae794dc42a5740c1cf64fe6bce186d8).
* [https://github.com/drud/wordpress](https://github.com/drud/wordpress/commit/e3d7c31739135df527c27a1acae26fc461950579)

## Results

### Works

* Simplified installation script and instructions for macOS [drud/ddev issue #98](https://github.com/drud/ddev/issues/98)
  * Confirmed that there are [install instructions on the readme](https://github.com/drud/ddev#installation-script).
  * Confirmed running `curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash` installs a binary and results in a success message displayed to the end-user.
  * Confirmed that the binary is in /usr/local/bin/
  * Confirmed that running `ddev version` shows the latest public release (v0.3)
* Upgrade notifications and instructions [drud/ddev issue #99](https://github.com/drud/ddev/issues/99)
  * Following the testing instructions here https://github.com/drud/ddev/pull/217.
  * `make clean`
  * `make DdevVersion=v0.2 darwin`
  * Running `ddev version` shows the message: "A new update is available! please visit https://github.com/drud/ddev/releases/tag/v0.3 to download the update!"
  * Running `ddev version` again doesn't show the message.
  * Confirmed a file exists at ~/.ddev/.update
  * Run "touch -mt 201705010101 ~/.ddev/.update"
  * Running `ddev version` again shows the message: "A new update is available! please visit https://github.com/drud/ddev/releases/tag/v0.3 to download the update!"
  * Running `ddev version` again doesn't show the message.
* Reworking and improving the `ddev list` commmand. [drud/ddev issue #153](https://github.com/drud/ddev/issues/153)
  * [This was already reviewed thoroughly here](https://github.com/drud/ddev/pull/160#issuecomment-297125804) and the output is still exactly as intended. Specifically, it matches the output the @rfay noted here https://github.com/drud/ddev/pull/160#issuecomment-297142178.
* Enforcing uniqueness of the project name across sites. [drud/ddev issue #136](https://github.com/drud/ddev/issues/136)
  * Checked out `git clone git@github.com:drud/wordpress.git`
  * `cd wordpress`
  * `ddev config` w/defaults and a sitename of "wordpress"
  * `ddev start`
  * Confirmed NAME of "wordpress" when running `ddev list`
  * Moved to another folder and re-ran the git clone to `ddev config` steps with another sitename of "wordpress".
  * Running `ddev start` results in the warning "Failed to start: a container in running state already exists for wordpress that was created at /Users/rmanelius/git/wordpress".
  * Re-running `ddev config` and renaming the 2nd sitename to "wordpress2" unblocks this warning and allows me to run `ddev start` on the 2nd site.
  * `ddev list` now shows both sites as "wordpress" and "wordpress2".  

### Fails

* Decisions on Linux and Windows support
  * Currently [have an open PR](https://github.com/drud/ddev/pull/220) to update README.
  * Roadmap is currently not updated to note future support for windows.

## Decisions
Based on the above manual testing, [ddev v0.4](https://github.com/drud/ddev/milestone/4) is NOT YET ready for release.

## Recommendations

* Name Uniqueness: We probably want to prompt the user to re-run `ddev config` as a solution to the name uniqueness item.

**Comment by rickmanelius** [comment]
# ddev v0.4 Review

## Executive Summary

Based on the following analysis, [ddev v0.4](https://github.com/drud/ddev/milestone/4) is ready for release!

## Milestone Overview

The intention of ddev v0.4 (see [Roadmap](https://github.com/drud/ddev/wiki/roadmap)) is to make it easy for end-users to get up running quickly. Also, the work to date has largely focused on macOS users and we need a strategy to broaden the scope of this product to include the other major OSs, notably Windows and Linux. To achieve this, we are focusing on the following:

The end-user features specific to ddev v0.4 are as follows:

* Simplified installation script and instructions for macOS
* Decisions on Linux and Windows support
* Upgrade notifications and instructions

In addition to features, we began to address items that will generally support and improve the project, including the following:

* Removing the proxy container if no sites are active.
* Reworking and improving the `ddev list` commmand.
* Enforcing uniqueness of the project name across sites.

## Testing
Performed by Rick Manelius as of 2017-05-12.

### Hardware Setup

I’m using a laptop with the following high level specifications:
* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.12.4

### Software Setup

* Xcode
* Go 1.8.1
* Docker 17.03.1-ce
* Git 2.11.0

### Repositories Used

* [https://github.com/drud/ddev](https://github.com/drud/ddev/commit/8f10148abae794dc42a5740c1cf64fe6bce186d8).
* [https://github.com/drud/wordpress](https://github.com/drud/wordpress/commit/e3d7c31739135df527c27a1acae26fc461950579)

## Results

### Works

* Simplified installation script and instructions for macOS [drud/ddev issue #98](https://github.com/drud/ddev/issues/98)
  * Confirmed that there are [install instructions on the readme](https://github.com/drud/ddev#installation-script).
  * Confirmed running `curl https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh | bash` installs a binary and results in a success message displayed to the end-user.
  * Confirmed that the binary is in /usr/local/bin/
  * Confirmed that running `ddev version` shows the latest public release (v0.3)
* Upgrade notifications and instructions [drud/ddev issue #99](https://github.com/drud/ddev/issues/99)
  * Following the testing instructions here https://github.com/drud/ddev/pull/217.
  * `make clean`
  * `make DdevVersion=v0.2 darwin`
  * Running `ddev version` shows the message: "A new update is available! please visit https://github.com/drud/ddev/releases/tag/v0.3 to download the update!"
  * Running `ddev version` again doesn't show the message.
  * Confirmed a file exists at ~/.ddev/.update
  * Run "touch -mt 201705010101 ~/.ddev/.update"
  * Running `ddev version` again shows the message: "A new update is available! please visit https://github.com/drud/ddev/releases/tag/v0.3 to download the update!"
  * Running `ddev version` again doesn't show the message.
* Reworking and improving the `ddev list` commmand. [drud/ddev issue #153](https://github.com/drud/ddev/issues/153)
  * [This was already reviewed thoroughly here](https://github.com/drud/ddev/pull/160#issuecomment-297125804) and the output is still exactly as intended. Specifically, it matches the output the @rfay noted here https://github.com/drud/ddev/pull/160#issuecomment-297142178.
* Enforcing uniqueness of the project name across sites. [drud/ddev issue #136](https://github.com/drud/ddev/issues/136)
  * Checked out `git clone git@github.com:drud/wordpress.git`
  * `cd wordpress`
  * `ddev config` w/defaults and a sitename of "wordpress"
  * `ddev start`
  * Confirmed NAME of "wordpress" when running `ddev list`
  * Moved to another folder and re-ran the git clone to `ddev config` steps with another sitename of "wordpress".
  * Running `ddev start` results in the warning "Failed to start: a container in running state already exists for wordpress that was created at /Users/rmanelius/git/wordpress".
  * Re-running `ddev config` and renaming the 2nd sitename to "wordpress2" unblocks this warning and allows me to run `ddev start` on the 2nd site.
  * `ddev list` now shows both sites as "wordpress" and "wordpress2".  
* Decisions on Linux and Windows support
  * The project readme and roadmap were updated to note the OSes we officially support as well as a placeholder for follow-ups by v1.0.
  * Technically this issue isn't closed from the perspective of getting an inventory of the Windows specific pain points and changes to our automated tests to include additional Linus distributions. However, from the end-user's perspective, the goal of this ticket for v0.4 has been achieved.

## Decisions
Based on the above manual testing, [ddev v0.4](https://github.com/drud/ddev/milestone/4) is ready for release!

## Recommendations

* Name Uniqueness: We probably want to prompt the user to re-run `ddev config` as a solution to the name uniqueness item.

**Comment by rickmanelius** [comment]
@cyberswat v0.4 is ready for release!

**Comment by rickmanelius** [comment]
Looks like we're good to go!
https://github.com/drud/ddev/releases/tag/v0.4
