### ISSUE TITLE
Security Audit & Recommendations

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#241]
Placeholder at the moment in order to address the goals of milestone v0.7. The intention of this ticket is to provide a timeboxed window for us for a top to bottom audit of what is provided by ddev v0.6 to determine if there are any obvious security areas to address.

**Comment by rickmanelius** [comment]
Given that this is more of a "meta" issue with an implied chunk of research, I suggest this as acceptace criteria:

* [ ] Review and decison on OSXFS https://github.com/drud/ddev/issues/282
* [ ] Drupal "Private" directory outside of webroot (may require https://github.com/drud/ddev/issues/189).
* [ ] Identification of any remaining hot button security items related to file mounts, OS user/groups, container defaults, etc.

Bonus items:

* [ ] Remove /etc/host dependency and replace with local DNS solution (possily related to https://github.com/drud/ddev/issues/277).

Switching actionable because beyond this list, I don't see any other major security items beyond what is already been tagged in this release.

**Comment by rickmanelius** [comment]
Related https://github.com/drud/ddev/issues/175

**Comment by rickmanelius** [comment]
No longer relevant for v0.7. Closing out.
