### ISSUE TITLE
Create 'local' platform plugin and tests

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#27]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Task

**Information**:
We need the the ability to create ddev environments from a 'local' resource plugin

**What you expected to happen**:
Using a git checkout of a Drupal site on the local filesystem you should be able to perform a `ddev add` and have a functional local development environment. The primary focus of this issue is to get local site installs working.

Done criteria:
- Latest versions of both D7 and D8 sites should work with this local plugin
- MySQL connection information should be printed alongside the site URL to assist the user in installing Drupal
- Pulling in assets such as a DB dump or a files backup is not required for this, but if it makes sense/saves time then it's fine as a stretch goal.
- Wordpress support is not a requirement for this ticket, but also fine as a stretch goal.
- Automated tests roughly at parity with ddev tests with newmedia plugin

Additional decisions:
- [decided] the user will be responsible for maintaining their own git checkout, not `ddev`

## Tasks for this issue:
- [x] Complete #41 - initial re-org and local file plugin.
- [x] Evaluate #24 and overall define our config file spec.
- [x] #47 Rework current workspace approach to facilitate site working directory approach.
- [x] #48 Update the `add` command to `start`, remove db/file import steps
- [x] #57 Create a new `config` command that will write our yml config based on prompted values
- [x] #85 Add tests for `ddevapp` package
- [x] #83 Add binary based test coverage again 

### Testing approach

- Should have tests to ensure the install page returns the correct HTTP status (both D7 and D8)
- Should parse MySQL connection info from the CLI output and ensure the connection is working
 - Dependent on git checkout decision point, update test to pull in a sample d7/d8 code base
