### ISSUE TITLE
v0.6 Release Checklist

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#281]
Remaining actions:

* [x] Review release (product owner)
* [x] Approve release (product owner and release manager)
* [ ] Create binaries (any DRUD maintainer)
* [ ] Draft release notes (release manager)
* [ ] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [ ] Create release (release manager)

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rickmanelius** [comment]
**Saving a snapshot of my pre-review starting point.**

# ddev v0.6 Review

## Executive Summary

Based on the following analysis, [ddev v0.6](https://github.com/drud/ddev/milestone/6) is NOT ready for release.

## Milestone Overview (Performance)

The intention of this milestone is to ensure end-users have a positive experience with the overall real and perceived performance of ddev while performing typical day to day tasks. At a minimum, ddev's performance should be on par (or better) than alternative solutions. Out of the box, ddev's containers should be right-sized in terms of resources allocation and app/service configurations based on community accepted best practices. Performance should be testable (automated and manually) to ensure that as ddev's feature set increases that performance is not accidentally and unnecessarily sacrificed. Summarizing our key areas of focus:

* PHP, Webserver, and Database Audit/Tuning
* Container Resource Audit and Tuning
* File System Review
* Competitor Performance Analysis
* Test (Automated and Manual) & Instructions
* Documentation (Our Results, What Drove Our Decisions, etc)

## Testing

Performed by Rick Manelius as of 2017-06-05.

### Hardware Setup

I’m using a laptop with the following high level specifications:

* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.12.4

### Software Setup

* Xcode
* Go 1.8.1
* Docker 17.06.0-ce-rc1
* Git 2.11.0

### Repositories Used

* [https://github.com/drud/ddev](https://github.com/drud/ddev/commit/249cda44050eaf02e17fc2e9c121d3a58907d251)
* [https://github.com/drud/drupal8](https://github.com/drud/drupal8/commit/9776f7a7157d9a43646143374fc15d2851938c62)

## Results

### Actively Testing

### Works

### Fails

## Decisions

Based on the following analysis, [ddev v0.6](https://github.com/drud/ddev/milestone/6) is NOT ready for release.

## Recommendations

**Comment by rickmanelius** [comment]
# ddev v0.6 Review

## Executive Summary

Based on the following analysis, [ddev v0.6](https://github.com/drud/ddev/milestone/6) is ready for release.

## Milestone Overview (Performance)

The intention of this milestone is to ensure end-users have a positive experience with the overall real and perceived performance of ddev while performing typical day to day tasks. At a minimum, ddev's performance should be on par (or better) than alternative solutions. Out of the box, ddev's containers should be right-sized in terms of resources allocation and app/service configurations based on community accepted best practices. Performance should be testable (automated and manually) to ensure that as ddev's feature set increases that performance is not accidentally and unnecessarily sacrificed. Summarizing our intended areas of focus:

* PHP, Webserver, and Database Audit/Tuning
* Container Resource Audit and Tuning
* File System Review
* Competitor Performance Analysis
* Test (Automated and Manual) & Instructions
* Documentation (Our Results, What Drove Our Decisions, etc)

Ultimately, we postponed a thorough analysis of the PHP, MySQL, and Nginx configurations because we're already using optimized configurations from known sources. Additionally, the largest performance factor was and has been issues surrounding Docker for Mac (see reference here https://docs.docker.com/docker-for-mac/osxfs/#performance-issues-solutions-and-roadmap). And while there are known performance gains associated with switching out the file systems, they come with additional costs/complexity that we were unwilling to take on. Therefore, the 3 areas we spent the most time on were the following:

* Competitor Comparisons
* Docker for Mac's User-Guided Cache
* Automation Tests for Repeat Performance Review

## Testing

Performed by Rick Manelius as of 2017-06-05.

### Hardware Setup

I’m using a laptop with the following high-level specifications:

* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.12.4

### Software Setup

* Xcode
* Go 1.8.1
* Docker 17.06.0-ce-rc1
* Git 2.11.0

### Repositories Used

* [https://github.com/drud/ddev](https://github.com/drud/ddev/commit/249cda44050eaf02e17fc2e9c121d3a58907d251)
* [https://github.com/drud/drupal8](https://github.com/drud/drupal8/commit/9776f7a7157d9a43646143374fc15d2851938c62)

## Results

### Works

* Implement user-guided caching for web mount [drud/ddev issue #253](https://github.com/drud/ddev/issues/253)
  * Confirmed the ":cached" value is added within the Docker compose configuration file.
  * Confirmed the D8 GUI install times match the new and improved results posted here https://github.com/drud/ddev/issues/253#issuecomment-303728071.
  * Reviewed @rfay's before/after cache tests https://docs.google.com/document/d/1nFbL1QekrVmKCcn8ENH25Um2MMh_30vfnVe2v1Uz6qE/edit.
* Automated Tests
  * While I did not specifically walk through the individual tests, evaluation of the results are highly encouraging. See below:
    * [CMS and Competitor Performance Matrix](https://docs.google.com/spreadsheets/d/1vgABX1VzQjd3B9478zfMj__LYT2NVmlnODKDuwUb0tQ/edit)
    * Automated test scripts before/after user-guided cache PR https://docs.google.com/document/d/1nFbL1QekrVmKCcn8ENH25Um2MMh_30vfnVe2v1Uz6qE/edit

## Decisions

Based on the following analysis, [ddev v0.6](https://github.com/drud/ddev/milestone/6) is ready for release. This is not to state that we cannot or will not address performance issues in the future, but that we've already put considerable effort in at this time and we will need to get more real world feedback as well as wait for improvements from the Docker for Mac offering (file and networking performance improvements).

## Recommendations

* Versioning: Note sure why a `ddev make darwin` specifies `cli: v0.4-30-g249cda44`. I would have figured we'd be on a v0.5 tag.
* Bug: I received the following when trying to spin up a d8 site right after destroying/rebuilding ddev 
  ERROR: for nginx-proxy  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint nginx-proxy (ee43850c08534bd3e641aaf1e2c47616b9febed54738d3c754e2657d93e95ec3): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
  * It looks like we need to prioritize the docker image pruning because `docker ps -a` shows some remaining images.
* System Resource Issues: When testing the user-guided cache issue for this review, my initial results for a D8 GUI install took 4 minutes. After a laptop reset, it dropped to 1:30. This seems to indicate that resource management across multiple containers or as a result of system resources can be an issue.

**Comment by rickmanelius** [comment]
@cyberswat Assigned to you and ready to release. Thanks!

**Comment by rickmanelius** [comment]
Since we've merged two milestones together and updated the roadmap, it's worth noting that I didn't explicitly re-review the security items that were moved in. However, they were reviewed at the time and I feel comfortable moving forward with this release.

**Comment by cyberswat** [comment]
https://github.com/drud/ddev/releases/tag/v0.6
