### ISSUE TITLE
Define Roadmap and Milestones Out to Version 2.0

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#430]
## What happened (or feature request):

* Feature request
* This is a child issue of the meta issue for all DRUD Roadmaps here https://github.com/drud/general/issues/109.

## What you expected to happen:

With the development and packaging/branding of ddev v1.0 largely completed, it's time to focus on the roadmap to version 2.0, with the largest change being the introduction of a front-end UI (see related issues below).

Proposed Acceptance Criteria Defined as Follows:

* [x] [ddev Roadmap](https://github.com/drud/ddev/wiki/roadmap) updated to include a minimum of 4 milestones, each featuring an overall intention and 2-5 tangible deliverables to support that intention.
* [x] An initial design and definition of the GUI endpoint for a 2.0 launch.
* [x] An initial inventory of backend development requirements to support that functionality.
* [x] An initial inventory of additional features that front-end will provide over the CLI version.
* [x] An initial inventory of non-dev needs (marketing, branding, documentation, etc) to support the 2.0 version of the project.

## Related source links or issues:

* #120 
* https://github.com/drud/general/issues/109

**Comment by rickmanelius** [comment]
Here's a document I'm using in the interim to start to shell out a roadmap for v2.0.
https://docs.google.com/document/d/1U8w-19mfufw93SJ9Mq_tybCfpOsAwSRiuGlYc3oGlMA/edit#

**Comment by rickmanelius** [comment]
I actually had a productive pass at this ^. I'll get a meeting scheduled with @andrew-c-tran next week to start reviewing.

**Comment by rickmanelius** [comment]
Here's my initial provisioning of the ddev v2.0 feature list spreadsheet. It's coming along and needs another 1-2 hours before it's ready to review with other members of the team. https://docs.google.com/spreadsheets/d/1oEi77sgX42BBsjHq6oOWnh3M0QNw8RnVzGCWox9scbg/edit#gid=0

**Comment by rickmanelius** [comment]
Here's a previous list of features (see this specific comment) https://github.com/drud/ddev/issues/120#issuecomment-312729262

**Comment by andrew-c-tran** [comment]
I think this is complete based on your roadmap @rickmanelius ?

**Comment by rickmanelius** [comment]
Final item on the issue summary checklist would be 1) backend requirements and 2) non-dev needs. As long as there are issues filed or trackable for each, we're golden.

## Backend Requirements

The biggest item is this item [Required modifications/extensions to ddev CLI to expose API to front-end dashboard](https://github.com/drud/ddev-ui/issues/2). This is more of a meta issue to address the overall strategy and the expectation will be to create tickets out of it.

## Non-dev Requirements

* Items already in place for ddev CLI that will need to be upgraded/extended:
  * Documentation site
  * Project website
  * Project readme.md
* New items specific to ddev UI
  * Video tutorials
  * Download/release strategy.
  * Public GitHub issue strategy.
  * Public Roadmap strategy.

It's worth providing additional information regarding some of the last few bullets. I wasn't thinking 100% clearly when we split off the ddev-ui work to a separate, private repo. This doesn't really allow for the wiki or issues to be publicly exposed and therefore we will need to have new homes. It will probably make sense to move the ddev UI roadmap and issues to the ddev issue queue, but that will also require us to use a common set of milestones. This is not the end of the world, but merely something that we will need to address.

Closing this issue because this meets the criteria and creating/filing additional tickets can be a subsequent task.
