### ISSUE TITLE
META: Triage/update backlog, roadmap, and project boards.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#534]
## Motivation

We've accumulated a bit of operational debt around milestones v0.9.x as a result of conference preparation, resourcing, other priorities, etc. As a result, we've lost some of the gains that were in place when we had a more clearly defined roadmap, milestones, planning board, and dev board.

## What you expected to happen:

Here's a working list of items that I feel are worth addressing:

* Closeout hibernate issues more than 3 months old.
* Remove all ddev issues on the project board that are not planned to address in the upcoming week.
* Remove all ddev issues on the sprint planning board that we don't plan on addressing in the next 2-3 weeks.
* Vet all issues in the 1-2 week queues to ensure they have all the requirements we agreed on upon in our community workflow document.
* Utilize this meta-issue as a checklist for any significant sub issues that need to be spun out.

Here are some wishlist items that may or may not be feasible/practical
* Attach any issues completed since v0.9.3 to a newly spun out v0.9.4 and tag an official release against that.

There may be other related issues to reference here, including decisions on semantic versioning, packaging/bundling between the CLI/GUI versions, etc. I'll leave them out for now and pull them into the normal workflow.

## REMAINING ACTIONS

* [x] Remove all incubate flags and replace w/hibernate
* [x] Remove all issues from all milestones to start with a clean slate
* [x] Stub out milestones to 1.5.0
* [x] Create placeholder issues out to 1.2.0 and assign to proper milestone

**Comment by rickmanelius** [comment]
I've completed an initial pass of closing out hibernate issues that are either already complete, stale, not reproducible or items we can wait for end-user feedback on before proceeding.

**Comment by rickmanelius** [comment]
Dev board is mostly up to date. Going to scrub the sprint planning board before moving to milestones/roadmap.

**Comment by rickmanelius** [comment]
Generated a first draft on the motivations/goals of a 2.0 roadmap. Will present at an internal team meeting today and based on that I'll use the feedback to inform modifications to the overall milestones towards this end state.

**Comment by rickmanelius** [comment]
I forgot to post this to the issue queue for a trail. Here it is https://docs.google.com/document/d/17E8JXe3MfkCfpzIJfh5NakEy_pSz2SaeVh_BuRP7pos/edit#heading=h.2suz25lmu55q.

**Comment by rickmanelius** [comment]
Adding a blocker because this is starting to impact work.

**Comment by rickmanelius** [comment]
Within the google doc, I drafted out a first revision of the roadmap milestones and key features. I would like to complete one additional pass and then put in a formal request for feedback from a techical/architecture perspective. Once we get past that, I can publish and start to create the milestones, assign issues in flight to those milestones, and start provisioning out issues to fill in the remaining gaps out 2-3 milestones. At that point, I will consider this issue closed and we can regain our previous prioritization and release cadence.

**Comment by rickmanelius** [comment]
Fixed the issue + milestones relationships because items were being left in the milestone they were originally filed versus released. Moving forward I will suggest that completed items match the release and not the originally planned milestone.

**Comment by rickmanelius** [comment]
Ok I think this is ready for a review. I think this warrants a conversation involving the team to sanity check, but I also know that it doesn't always benefit us from a time perspective to have that many eyeballs and burn that many hours in a meeting. At a minimum, I would want @cyberswat and @rfay to review with @beeradb and @tannerjfco certainly welcome/encouraged to weigh in. It looks like tomorrow (Thursday) at 10 AM could work for a meeting and that would give everyone time to review the Google doc (https://docs.google.com/document/d/17E8JXe3MfkCfpzIJfh5NakEy_pSz2SaeVh_BuRP7pos/edit#heading=h.gbx5jpvy7950) where I put the proposed roadmap at the bottom. Upon going through this sanity check, I can consider this unblocked and start to provision issues on the roadmap and that should basically give @cweagans and @rfay runway for months as well as a set of clearly defined set of targets with each week.

Calendar invite is going out. Feel free to accept/decline to participate or not. Feel free to leave comments in the doc in prep for the meeting.

**Comment by rickmanelius** [comment]
We met as a team and updated the document. Overall there were a few key items to touch on.

* The docker compose/database setting file management items need to have a least some decision for now with the understanding that we will probably revisit before the end of this roadmap.
* Usage statistics was missed and we all agree we want very early in on this roadmap. See #532.
* File performance for D8/TYPO3 was noted as a high priority.

Next Actions
* Another pass at this draft
* Publish to the wiki as a starting point
* Create/update issues to begin placing out 2-3 milestones out.
* Remove incubate/milestone metadata for items that fall outside of our immediate needs.

**Comment by rickmanelius** [comment]
Removed blocker because I believe we at least have runway for one week with current issues and members of the team can reference the current WIP roadmap to make informed choices if/when that runway is almost gone.

**Comment by rickmanelius** [comment]
I did another pass of the roadmap and with the updated edits I feel confident that this now serves it purpose a starting point. Going to run through a grammar/spelling/formatting check and then move it to the official location before taking on the final set of tasks to start provisioning/updating issues and tagging with the appropriate milestones.

**Comment by rickmanelius** [comment]
Updated the roadmap contained in the GitHub repo. Moving onto provisioning of the milestones and issues up to 1.2.0.

**Comment by rickmanelius** [comment]
Considering this closed and we can pick up post sprint planning to get remaining items stubbed out.
