### ISSUE TITLE
v1.0.0 Release Checklist

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#560]
## Remaining actions:

* [ ] Review release (product owner)
* [ ] Approve release (product owner and release manager)
* [ ] Create binaries (any DRUD maintainer)
* [ ] Draft release notes (release manager)
* [ ] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [ ] Create release (release manager)
* [ ] Update any package managers to point to new release (release manager)
* [ ] In accordance with [U.S Department of Commerce cryptographic legislation](https://www.bis.doc.gov/index.php/policy-guidance/encryption/encryption-faqs/15-policy-guidance/encryption) we need to send an email drafted from [this template](bis_template.md) to crypt@bis.doc.gov and enc@nsa.gov notifying the BIS of publicly available source code with encryption technology on major point releases.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rickmanelius** [comment]
## Additional Information

This release has been blocked for a variety of reasons for both technical and documentation related reasons. The biggest two are 1) ensuring we are fully ready and going to commit to [semantic versioning](https://github.com/drud/ddev/issues/352) and 2) ensuring we have our readme.md and documentation in order. Given that a full docs overhaul is too large a mountain to climb given current priorities, I'm going to suggest we focus on accuracy and consider it sufficient as is for v1.0.0 while prioritizing an overhaul along the roadmap beyond 1.0.0.

Finally, we had committed to some additional Windows OS support items in our original roadmap. If we can get those in conjunction with the items above, then great! Otherwise, because they don't introduce breaking changes, waiting to v1.Y.Z versions seems like a reasonable compromise.

One thing that is blocking #352 (Semantic Versioning) is getting the initial roadmap done (#534) so we have some sense of confidence that the Windows related support changes won't introduce significant break changes.

**Comment by rickmanelius** [comment]
Oh, and #415 and other items related to managing settings.php or docker-compose.yml files would fall within the scope of the Semver conversation.

**Comment by cweagans** [comment]
> In accordance with U.S Department of Commerce cryptographic legislation we need to send an email drafted from this template to crypt@bis.doc.gov and enc@nsa.gov notifying the BIS of publicly available source code with encryption technology on major point releases.

😲 Do we even have any crypto code in ddev? Also, the two non-email links in this point are broken.

**Comment by rickmanelius** [comment]
@cweagans Thanks for catching the broken links because we've been carrying for the template release by release and those were simply stale references that we can update.

As for crypto code. The mere fact that we use ssh lumps us into this, or so says our lawyer with tons of open source experience and wanting us to keep all of our ducks in a row :)

**Comment by rickmanelius** [comment]
Moving this to "blocker" state and assigning to hold myself accountable to the team to get all the tagged v1.0.0 issues moving forward.

**Comment by rfay** [comment]
Closing this. It can be reopened when it has more detail.
