### ISSUE TITLE
v0.15.1 Release Checklist Due 2018-03-12

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#726]
Remaining actions:

* [x] Review release (product owner)
* [x] Approve release (product owner and release manager)
* [ ] Create binaries (any DRUD maintainer)
* [ ] Draft release notes (release manager)
* [ ] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [ ] Create release (release manager)

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rickmanelius** [comment]
In order to use effectively use the new packaging in #724, we need a new release tagged. This was already reviewed/merged, so we just need to cut the release.

**Comment by rfay** [comment]
Yeah, IMO we don't need a new release for it, the containers are the same. I'm adding the new tar.xz to the v0.15.0 release.

**Comment by rfay** [comment]
Closing.
