### ISSUE TITLE
v0.18.0 Release Checklist Due 2018-05-01

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#794]
Remaining actions:

* [ ] Review release (product owner)
* [ ] Approve release (product owner and release manager)
* [ ] Create binaries (any DRUD maintainer)
* [ ] Draft release notes (release manager)
* [ ] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [ ] Create release (release manager)

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rickmanelius** [comment]
Moving the target release date to Thursday, May 3rd to account for the time I'll need before getting an end-to-end review.

**Comment by rickmanelius** [comment]
Current diff https://github.com/drud/ddev/compare/v0.17.0...HEAD

**Comment by rickmanelius** [comment]
So there is quite a bit to retest on this one. Of the 20 closed issues/PRs, I think these are the highest value from the perspective of an end-user

* [Windows Sudo Package #798](https://github.com/drud/ddev/issues/798)
* [Windows Installer #786](https://github.com/drud/ddev/issues/786)
* [Accessing logs on stopped containers #719](https://github.com/drud/ddev/issues/719)
* [ddev taking over config.yml, docker-compose.yml #762](https://github.com/drud/ddev/issues/762)
* [All config.yml to use default container image metadata #713](https://github.com/drud/ddev/issues/713)
* [Fix Docker Compose overrides and ordering #815](https://github.com/drud/ddev/issues/815)
* [Xdebug hostname #736](https://github.com/drud/ddev/issues/736)
* [Environment Variables Support](https://github.com/drud/ddev/issues/757)
* [Terminal chacter length #799](https://github.com/drud/ddev/issues/799)
* [Terminal color on Windows #363](https://github.com/drud/ddev/issues/363)
* [Stack exchange/Stackoverflow support #702](https://github.com/drud/ddev/issues/702)

**Comment by rickmanelius** [comment]
As @rfay mentioned, there are several one-off PRs in the nginx repo that also are worth noting in the release notes https://github.com/drud/docker.nginx-php-fpm-local/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed.

**Comment by rfay** [comment]
Please don't forget https://github.com/drud/ddev/pull/803, for windows warning removal.

**Comment by rickmanelius** [comment]
Ah yes I missed that one because I didn't have it properly tagged. Updated the issue metadata on #803 and now I need to push to get my testing pass started.

**Comment by rfay** [comment]
Key issues for end user release notes:
- [ ] simplified xdebug
- [ ] Windows installer with sudo (no more manual hosts maintenance)
- [ ] Upgrade path: ddev owns docker-compose.yaml, versions config.yaml
- [ ] Added nodejs/npm/yarn and patch to web container
- [ ] Stack Overflow for common support issues and offbeat usages
- [ ] Bug fixes

**Comment by rfay** [comment]
Testing Procedure:

MacOS:
- [ ] D8 config and web install
- [ ] XDebug test with PHPStorm
- [ ] Upgrade an existing site with this version (`ddev config`) and start it, verify correct behavior.
- [ ] Verify that `ddev config` on existing site updates the version and removes the containers
- [ ] Verify that specified containers in config.yaml still work to override a container.
- [ ] Verify nodejs, npm, yarn, patch in web container
- [ ] Verify accessing logs on stopped containers (just stop site and use `ddev logs`)
- [ ] Use a docker-compose.override.yaml and make sure it works correctly.
- [ ] Use `ddev ssh` with a large terminal and verify correct behavior
- [ ] TYPO3 config and install
- [ ] Verify that TYPO3 trusted hosts pattern is properly inserted.

Windows:
- [ ] Install with installer
- [ ] D8 config and web install
- [ ] XDebug test with PHPStorm
- [ ] Use `ddev ssh` with a large terminal and verify correct behavior
- [ ] Make sure the warning about running windows as root is gone. Verify files are created as correct user on host.
- [ ] Verify that ugly characters are gone now and coloring is done right

**Comment by rickmanelius** [comment]
The last thing is on me and @nearlythere to get the blog/email announcements and then we can call this one closed.
