### ISSUE TITLE
Roadmap Clean-up

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#832]
## What happened (or feature request):

[The roadmap](https://github.com/drud/ddev/wiki/roadmap) has not been updated to reflect the recent releases. It also has a few inaccuracies because certain milestones (such as CMS support in v1.2.0 and upgrade path support in v1.6.0) have already been addressed. To that end, I would hope for the following.

## What you expected to happen:

* [x] Update the "Previous Release" section to link to all completed milestones (@dclear)
* [x] Remove the language regarding the existing milestones v1.2.0 and v1.6.0 in the wiki, and re-number the milestones in the new order (@dclear)
* [x] Rename the GitHub milestones to reflect the roadmap (@rickmanelius)
* [ ] Review and update the roadmap based on new goals and objectives (@rickmanelius)

**Comment by rickmanelius** [comment]
Hi @dclear. Thanks for updating the previous releases at the bottom. To answer your question, yes jsut remove the stanzas completely and then renumber (so 1.3 becomes 1.2, 1.4 becomes 1.3). As for the actual [ddev GitHub milestones](https://github.com/drud/ddev/milestones) that had issues attached to them, I'm open to suggestion. It might be kindof tedious to move issues between milestones, so I would suggest that we simply move [the open/closed issues on v1.2](https://github.com/drud/ddev/issues?q=milestone%3Av1.2.0+is%3Aclosed) to new milestones or simply unattach a milestone altogether. My preference is to keep completed issues attached to the version of DDEV where it was closed/completed (for historical tracking purposes). Open items can move to another milestone or detach.

Let me know if that makes sense or if you have any follow-up questions!

**Comment by dclear** [comment]
hi @rickmanelius : yes, this makes sense - thanks! I'll ping if I have additional questions.

**Comment by dclear** [comment]
ok tossing this back to you @rickmanelius . The roadmap [is updated](https://github.com/drud/ddev/wiki/roadmap), re-ordered, and the open issues have moved to new milestones, reflecting the new order.

**Comment by rickmanelius** [comment]
Looks good. I'll take from here to audit and ensure they are now matching up with goals that we're outlining for the next 30/60 days. Changing the assignment back to me and updating labels.

**Comment by rickmanelius** [comment]
I ended up proceeding on this and added caveats regarding the fluidity of the roadmap after 3 milestones out. These more closely mirrors our posture of having longer-term intentions while being flexible should objectives change. Still, we want to make sure these bigger rocks/objectives don't continue to push off into the future, so we need to keep on them while allowing the smaller issues to form around them.

To that end, I believe I've met the objective of this issue because I feel like this gives me more clarity regarding prioritization. Follow-up filing of and defining issues should fit within our sprint planning process.
