### ISSUE TITLE
v0.20.0 Release Checklist Due 2018-06-19

### ISSUE THREAD

**Issue by dclear** [drud/ddev#907]
Remaining actions:

* [x]  Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [x] Create release (release manager)
* [x] Update Roadmap (TPM/release manager)
* [ ] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rickmanelius** [comment]
I've scheduled time tomorrow morning to review, but it would be helpful to get a punchlist together and ensure all committed code is attached via the v0.20.0 milestone. This way we can focus on the specific items that will need a final end-user review before we tag a release.

I'll start triaging this afternoon unless someone else beats me to it. Thanks!

**Comment by rfay** [comment]
I think the key user-facing changes in v0.20.0 are:
* sudo capability, which solves a number of user problems #935, solves #918, #919, #920 
* Added packages php-memcached (#923) and rsync (#912)

Important other changes (don't need callout but do need testing):
* d6/7/8 file permissions, #916 and #715 

git log --oneline v0.19.0..upstream/master
79e7ba34 Allow a user to issue commands with sudo, fixes #918, fixes #919, fixes #920 (#935)
2432cd6a Improve Drupal 6/7/8 file permissions, fixes #715 (#916)
b564efad Add Composer Setup Example for TYPO3 (#929)
156045e7 Improve reliability with a more unique tmpdir and outdir (#914)
374168cd Install php-memcached extension on web container (#923)
6975fa02 Fix broken containers resulting from CRs in scripts (#913)
4e9f3d3b Provide descriptions for Windows installer components, fixes #903 (#904)
da58b5bd Add release checklist (#908)
42b69c85 Add rsync to nginx-php-fpm-local, fixes #867 (#912)
34ce9b7e Add windows 10 docker toolbox testing to buildkite, fixes #705 (#902)
4b248be6 Create typo3conf/ if it doesn't exist, fixes #741 (#906)
51c3c890 Fix Slack channel formatting, add link to ddev releases page. (#901)

**Comment by rfay** [comment]
Note that one more commit will be required for the release process, updating all images to v0.20.0

**Comment by rickmanelius** [comment]
@rfay Excellent! Thanks for putting this together. Question, with the php-memcached extension in, any reason to not also pull https://github.com/drud/ddev/pull/927 (after review)?

Looks like we have a fairly straightforward test of 3 end-user items. Thanks!

**Comment by rfay** [comment]
I haven't tested it, and we're at the deadline. That seems like a good reason not to pull #927 yet.

**Comment by rickmanelius** [comment]
Fair enough. We'll move to the next release.

**Comment by rickmanelius** [comment]
Sorry for the comment noise. Moved all non-v0.20.0 issues to the next milestone (some of them are docs only, but it's good to stay disciplined here). Will start the review this afternoon or early tomorrow morning.

**Comment by rickmanelius** [comment]
Here is my working copy so far.

# ddev v0.20.0 Review

## Executive Summary

Based on the following analysis, [ddev v0.20.0](https://github.com/drud/ddev/milestone/31) is not ready for release.

## Milestone Overview (TODO)

TODO

* UX/DX: 
* Documentation: 
* Security: 

Additionally, there are...

## Testing

Performed by Rick Manelius as of 2018-06-25

### Hardware Setup

I’m using a laptop with the following high-level specifications:

* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.13.4

### Software Setup

* Xcode
* Docker 18.03.1-ce
* Git 2.15.1

### Repositories Used

* [DDEV 79e7ba3](https://github.com/drud/ddev/commit/79e7ba34b971d5d9497c76804ceace15b1988d8f)
* [Drupal 7.59](https://www.drupal.org/project/drupal/releases/7.59) 

### Preparation

* ddev 
  * `git checkout 79e7ba3`
  * `make clean && make darwin`
  * `ddev version` => v0.19.0-12-g79e7ba34

## Results

### Working

### Needs Work

## Decisions

Based on the following analysis, [ddev v0.20.0](https://github.com/drud/ddev/milestone/31) is not ready for release.

## Recommendations

* TODO

**Comment by rickmanelius** [comment]
@rfay @dclear I've completed my review of the end-user facing functionality (see updated comment above). There was only one snag that occurred during the toggle between v0.19.0 and the latest commit. I don't think it's a repeatable issue, but it's worth noting in case anyone has a v0.19.0 projext and upgrades. It's almost like Docker didn't recognize that a copy of the site already existed and spun up a separate copy that I couldn't then access via ddev rm but it would show up in ddev list.

Beyond that, the items look good. Thumbs up and lets get this out!

**Comment by rickmanelius** [comment]
@dclear If you don't mind doing a quick roadmap update we can close this out.

**Comment by dclear** [comment]
@rickmanelius : definitely, will get this done today

**Comment by dclear** [comment]
updated roadmap; closing .20 milestone, closing project board
