### ISSUE TITLE
v1.0.0 Release Checklist Due 2018-07-19

### ISSUE THREAD

**Issue by dclear** [drud/ddev#950]
Remaining actions:

* [x]  Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [x] Create release (release manager)
* [x] Update Roadmap (TPM/release manager)
* [x] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rickmanelius** [comment]
Here is my working copy so far.

# ddev v1.0.0 Review

## Executive Summary

Based on the following analysis, [ddev v1.0.0](https://github.com/drud/ddev/milestone/8) is not ready for release.

## Milestone Overview (@TODO)

@TODO

## Testing

Performed by Rick Manelius as of 2018-07-18

### Hardware Setup

I’m using a laptop with the following high-level specifications:

* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.12.4

### Software Setup

* Xcode
* Docker 18.03.1-ce
* Git 2.15.1

### Repositories Used

* [DDEV f3514b56](https://github.com/drud/ddev/commit/f3514b56b632e397e5c6f3880bbafa1a5ee87da7)
* [Drupal 7.59](https://www.drupal.org/project/drupal/releases/7.59) 

### Preparation

* https://github.com/drud/ddev/pull/990
* `git checkout f3514b56`
* `make darwin`
* `ddev version` => v0.20.0-24-gf3514b56

## Results

### Working

### Needs Work

## Decisions

Based on the following analysis, [ddev v1.0.0](https://github.com/drud/ddev/milestone/8) is not ready for release.

## Recommendations

* TODO

**Comment by rickmanelius** [comment]
Current diff https://github.com/drud/ddev/compare/v0.20.0...HEAD

**Comment by rickmanelius** [comment]
Here are the notable, end-user items:

* Improvements of settings file management (https://github.com/drud/ddev/issues/468)
* Support for fully qualified domain names or FQDNs (https://github.com/drud/ddev/issues/868)
* Start, stop, and remove all projects at once (https://github.com/drud/ddev/issues/952)
* Updated docs regarding our expanded Windows 10 support (https://github.com/drud/ddev/issues/896)

Lots of bug fixes and enhancements across the board for Drupal and TYPO3.

**Comment by rickmanelius** [comment]
### Working

* Improvements of settings file management (https://github.com/drud/ddev/issues/468)
  * See test results [here](https://github.com/drud/ddev/pull/990#issuecomment-405400467) and [here](https://github.com/drud/ddev/pull/990#issuecomment-406098202).
  * CONFIRMED
* Support for fully qualified domain names or FQDNs (https://github.com/drud/ddev/issues/868)
  * See test results [here](https://github.com/drud/ddev/pull/988#pullrequestreview-136685402), which I reran successfully.
  * CONFIRMED
    * Still suggest a better warning when router fails. Perhaps suggest that it could be a collision. "Failed to start drupal-7.59b: ddev-router failed to become ready: health check timed out: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=unhealthy"

I need to pick up the rest tomorrow.

**Comment by andrewfrench** [comment]
@rickmanelius Absolutely &mdash; good catches! Fixes are in #1000 and #1001.

**Comment by rickmanelius** [comment]
Given the two approved PRs, this is now good to go from my end. Approving this release.

**Comment by rickmanelius** [comment]
Blog/newsletter sent, Tweets tweeted, and roadmap revised. Closing!
