### ISSUE TITLE
v1.1.0 Release Checklist Due 2018-08-15

### ISSUE THREAD

**Issue by dclear** [drud/ddev#994]
Remaining actions:

* [x]  Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [x] Create release (release manager)
* [x] Update Roadmap (TPM/release manager)
* [x] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by rfay** [comment]
Artifacts for testing v1.1.0 are at https://circleci.com/gh/rfay/ddev/637#artifacts/containers/0

**Comment by rickmanelius** [comment]
Current diff https://github.com/drud/ddev/compare/v1.0.0...HEAD

**Comment by rickmanelius** [comment]
Based on the release notes and diff, I believe these are the end-user features to focus on.

* [files-import](https://github.com/drud/ddev/pull/1037)
* [drud-s3 pluging](https://github.com/drud/ddev/issues/998)
* [covert to docker volumes, snapshotting](https://github.com/drud/ddev/issues/714)
* [memcached](https://github.com/drud/ddev/pull/927)
* [hostname clean ups](https://github.com/drud/ddev/issues/831)
* [drush on host machine](https://github.com/drud/ddev/issues/454)

Luckily, all but one I've tested before at some level. The drush command is the only one I'll be using for the first time.

**Comment by rickmanelius** [comment]
Here is my working copy so far.

# ddev v1.1.0 Review

## Executive Summary

Based on the following analysis, [ddev v1.1.0](https://github.com/drud/ddev/milestone/32) is not ready for release.

## Milestone Overview (@TODO)

@TODO

## Testing

Performed by Rick Manelius as of 2018-08-14

### Hardware Setup

I’m using a laptop with the following high-level specifications:

* MacBook Pro: Retina 15-inch Mid 2015
* 2.2 Ghz Intel Core i7
* 16 GB 1600 MHz DDR3 RAM
* 250 GB Hard Drive
* macOS Sierra 10.12.4

### Software Setup

* Xcode
* Docker 18.03.1-ce
* Git 2.15.1

### Repositories Used

* 

### Preparation

* TODO

## Results

### To Test

* [files-import](https://github.com/drud/ddev/pull/1037)
* [drud-s3 pluging](https://github.com/drud/ddev/issues/998)
* [covert to docker volumes, snapshotting](https://github.com/drud/ddev/issues/714)
* [memcached](https://github.com/drud/ddev/pull/927)
* [hostname clean ups](https://github.com/drud/ddev/issues/831)
* [drush on host machine](https://github.com/drud/ddev/issues/454)

### Working

### Needs Work

## Decisions

Based on the following analysis, [ddev v1.1.0](https://github.com/drud/ddev/milestone/32) is not ready for release.

## Recommendations

* TODO

**Comment by rickmanelius** [comment]
Noting something that came up in my testing. I'd like to get ahead of that...

* [files-import](https://github.com/drud/ddev/pull/1037)
  * Set up Drupal 7.59 w/defaults.
  * `drush site-install standard --db-url=mysql://db:db@db/db -y`
  * Verified working D7 site
  * Created a drush site archive with `ddev exec drush ard`
  * Attempt 1: Interfactive
  	* `ddev import-files`
  	  * Recommendation: Add "source" to the instructions to help delineate that this is not the destination path or the path to import. That is: "Provide the path to the source directory or archive you wish to import."
  	  * Properly failed if I added an incorrect filename with "Failed to import files for drupal-7.59: invalid asset: file not found"
  	  * Properly identified the file
  	  	* REGRESSION. I thought we used to have a prompt for the --extract-path string?
  * Attempt 2: Flags
    * Invalid archive and extract path
      * `ddev import-files --src file.txt --extract-path blah` => "Failed to import files for drupal-7.59: invalid asset: file not found"
    * Valid archive, invalid extract path
      * `ddev import-files --src db.20180815_104847.tar.gz --extract-path blah` => Reports "Successfully imported files for drupal-7.59"
      	* ISSUE. An invalid path should not result in a success message. We should confirm the path exists and, if not, tell the user the path is wrong.
    * Valid archive, valid extract path
      * `ddev import-files --src db.20180815_104847.tar.gz --extract-path html` => Success message and this worked.
  * Things not tested
  	* All archive formats (previously confirmed tar, gzip, and tar.gz)
  	* Directories instead of archives.
  * FAILED.
    * I feel strongly that the success message for an invalid path needs to be a warning/error and not a success.
    * I think the interative prompt needs the extract-path. Coupled with the incorrect success message (previous bullet), it's hard for an end-user to debug when there is 1) no way to add that flag and 2) they are getting a false positive.

**Comment by rickmanelius** [comment]
Completed reviews on 4 of the 6 items. May have to wait a few hours until I get back to the rest.

**Comment by rickmanelius** [comment]
Done with my review. As noted, there is one fail (IMHO) and two recommendations. I know import-files is also not a typical end-user feature, so if this is simply not something we can turn around in a day, I'm good with filing a followup issue for the next sprint and still approving the release. The other features are still working and I'm happy how this release has turned out!

**Comment by rickmanelius** [comment]
BTW, based on the latest PR... we are approved for release.

**Comment by dclear** [comment]
over to me to update roadmap, close milestone and roll out next release issue checklist

**Comment by dclear** [comment]
* updated the wiki roadmap page; created next release checklist
* closing this, the milestone and the board
